{% set version = "3.10.6" %}

package:
  name: geos
  version: {{ version }}

source:
  url: https://github.com/libgeos/libgeos/archive/{{ version }}.tar.gz
  sha256: 42c9e048b7103ecfce784e82aef2bcd1afec340b4483295cb3ff3817960789b1
  patches:
    - patches/0001-unconditional-geos-pc.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # pretty poor backcompat.  SO name changes each release.
    # https://abi-laboratory.pro/tracker/timeline/geos/
    - {{ pin_subpackage('geos', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
 
test:
  commands:
    - geos-config --version  # [not win]

about:
  home: https://trac.osgeo.org/geos/
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: Geometry Engine - Open Source
  description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology
    Suite (JTS). As such, it aims to contain the complete functionality of
    JTS in C++.
  doc_url: https://trac.osgeo.org/geos/
  dev_url: https://github.com/libgeos/libgeos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
    - xylar
