{% set version = "3.8.0" %}

package:
  name: geos
  version: {{ version }}

source:
  url: https://github.com/libgeos/libgeos/archive/{{ version }}.tar.gz
  sha256: f8b260151fc8aa6bdf5c74550ea089eeb85d8623bb7ccaf9380e90c815c4d12b
  patches:
    - xmltester.cpp.patch  # [win]
    - 0001-fix-xmltester.patch
    - 0002-remove-bad-test.patch  # [linux and not x86]
    - 0003-removed-bad-issue.patch  # [linux and aarch64]
    - 0004-remove-failing-geos-test.patch  # [linux and not x86]
    - 0005-remove-failing-linnearref-test.patch  # [linux and not x86]

build:
  number: 1
  skip: True  # [win and vc<14]
  run_exports:
    # pretty poor backcompat.  SO name changes each release.
    # https://abi-laboratory.pro/tracker/timeline/geos/
    - {{ pin_subpackage('geos', max_pin='x.x.x') }}

requirements:
  build:
    - msinttypes  # [win]
    - cmake  # [win]
    - automake  # [not win]
    - libtool  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]

test:
  commands:
    - geos-config --version  # [not win]

about:
  home: http://trac.osgeo.org/geos/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Geometry Engine - Open Source'
  description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology
    Suite (JTS). As such, it aims to contain the complete functionality of
    JTS in C++.
  doc_url: http://trac.osgeo.org/geos/
  dev_url: https://github.com/libgeos/libgeos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
