{% set version = "3.7.3" %}

package:
  name: geos
  version: {{ version }}

source:
  url: https://github.com/libgeos/libgeos/archive/{{ version }}.tar.gz
  sha256: 3cf7c15e6bbc5f32602bfef0748bfe0e1098e55289e8b75f975bcda546d3e20b
  patches:
    - xmltester.cpp.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    # pretty poor backcompat.  SO name changes each release.
    # https://abi-laboratory.pro/tracker/timeline/geos/
    - {{ pin_subpackage('geos', max_pin='x.x.x') }}

requirements:
  build:
    - msinttypes  # [win]
    - cmake  # [win]
    - automake  # [not win]
    - libtool  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - geos-config --version  # [not win]

about:
  home: http://trac.osgeo.org/geos/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Geometry Engine - Open Source'
  description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology
    Suite (JTS). As such, it aims to contain the complete functionality of
    JTS in C++.
  doc_url: http://trac.osgeo.org/geos/
  dev_url: https://github.com/libgeos/libgeos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
