# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RCQW91N9R13wGYLa/eGic6p8qTLfmXmfLO4Zftxgkh056YY8dYXHdRZVKS3rL+8y2v/asT53CCFYXG/49S6sFsC0M294K7PDsgGTz1xBshF2ES6bpQwAUe1kJJcV1AznOT2yrhxaZX8bi/Ibrq2at5Bycv1bPpkABtvFld+JAwEt/xDloI6Jnglf2btvlGQptunEe2vnGyljT2EmkCrRFi+OyU9c1xS5hvqv4PMbZ92kaO00wB0BQOBXtuf1dItp9y4dCr/fjMMfYleJDL26kD+xwHcxwy7GXrMITwZz74J+2TT8KJEubnsme594+P7WeeUixTpU0aosPVjSWnYkv8Z9EORP1SUdUo3Y5buJWDLLs8fOPIzMKEwkQDMsvUateiHVhS/P2/QDd8NxEpUcL+OEl4K2DI6FndgO4qwNlSfzzZ06ExZN/wXjejh10lumf7To23dg4x+u7WQ7QPXMvZRiGpoVw6yon4tN7bbG2RQYmXJehJDR2Z9qVdeUMYCxQd3FAAeeSU6BeZLcSxiuCEuhZJaxJ2+8aZBBc7P2u0/ONk0Kb/nYSySUVF7SoM3g/RRHs5ws7Ox4MvkI50Yv8GmYRfTfjjOm9S+5jL9EJcE2dRxusGwmrmMJUR7dx92n5pyHomHgV23M3ZSAcvr/bFZRTYPpZ1Xtx8EnmjLADM8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml

  - conda config --remove channels defaults --force

  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
