travis:
  secure:
    BINSTAR_TOKEN: GiVZtIHPc0hjy8rk+czPaquRhqRkm1er8ubeVXI3/o23jz+JfedM54d8sOgdCJ7yGm6o5atlJ5XnxkViLQL7Gv/LBJPQxXy5YUjW8WxBFqhDJdjjX9lTV8guQqTpp5eV4qz2lhCoMBibUoOdkmkInF3HieWnJTDg7d9FIPvy4J05pVnlDhKvhMhAtMkqysBAvWcwZdCHP6sQBZ250KRZcKD3WudP1oTZZwRB1jXrB6qH3b7/Nz7YSXK9Sv7tawYZmb+Cam5YLr79+VVae2yWWaI0zwDpyR8rmOjiGQxJENXuNBTEP5W9wYQtbE5sha9eQ4QObcBfkm5b3NVR4wAGr1Z1ddHlXyFEU/Itc7HW5rZsyYloD7XQtDJdOrdg3u+h92weYwUJWXOBB71FrKYO1VcD640e33Uw3ehhN563UTU9aD933p3GZJKwe2xYwRUKp1VR2zKf6QCpWeZRNU9OXAGVFEdM/orIO1cBCG/BwF+iFEhvxtr2/V1gvwnzrRiMrsc/6neLJuM7tBBac6sVs8vGc4nK7VnNKbyLNZj9eQy8V4YOPlE+EsbI1RzNEgduywdP3A8H8bYWE9/3siaQkt1yhWV71gMVxmK7Ug5jB47agLU/er9vSpbjirgTgIqhgqVsjC5czQ/hBTWVpqQc/GOryChRY9XBz8ElpjrWil4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
